apiVersion: 1

# 数据源列表
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: weather_db
    user: weather_user
    secureJsonData:
      password: StrongPassword123!
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    version: 1