{
 "title": "Weather-Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "var_city_name",
    "label": "城市名称",
    "query": "select distinct city_name from weather_now"
   }
  ]
 },
 "panels": [
  {
   "title": "城市天气温度、湿度走势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT city_name as \"城市名称\", update_time as \"更新时间\", temp as \"天气温度\", humidity as \"天气湿度\" FROM weather_now where city_name = '${var_city_name}'"
    }
   ]
  },
  {
   "title": "各城市最新温度和湿度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT city_name as \"城市名称\", temp as \"天气温度\", humidity as \"天气湿度\" FROM weather_now where update_time = (select max(update_time) from weather_now)"
    }
   ]
  },
  {
   "title": "各城市最新温度和湿度对比",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT city_name as \"城市名称\", temp as \"天气温度\", humidity as \"天气湿度\" FROM weather_now where update_time = (select max(update_time) from weather_now)"
    }
   ]
  },
  {
   "title": "当前筛选城市最新数据",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT city_name as \"城市名称\", update_time as \"更新时间\", insert_ts as \"插入时间\", created_at as \"创建时间\", temp as \"天气温度\", humidity as \"天气湿度\" FROM weather_now \r\nwhere city_name = '${var_city_name}' \r\norder by insert_ts desc\r\nlimit 10"
    }
   ]
  }
 ]
}